# Generated by Django 5.1 on 2024-09-02 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_answer_answer_ans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ans',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_type', to='api.category'),
        ),
    ]
