# Generated by Django 5.1 on 2024-08-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_passby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passby',
            field=models.CharField(max_length=100),
        ),
    ]
